name: CD

on:
  repository_dispatch:
    types: [cd]

defaults:
  run:
    shell: pwsh

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Setup psake
      run: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted; Install-Module -Name psake
    - name: Prepare to deploy
      run: Invoke-psake cd
    - name: Push API image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./src/Delights.Api/Dockerfile
        push: true
        tags: |
          stardustdl/delights:api
    - name: Push client image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./src/Delights.Client/Dockerfile
        push: true
        tags: |
          stardustdl/delights:client
    
